services:
  trade-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade-stream
    ports:
      - "8080:8080"
    volumes:
      # Mount config file for easy updates without rebuilding
      - ./config/config.yaml:/app/config/config.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trade-stream-network

networks:
  trade-stream-network:
    driver: bridge
